export const FETCHING_DASHBOARD_DATA = 'FETCHING_DASHBOARD_DATA';
export const DASHBOARD_DATA_SUCCESS = 'DASHBOARD_DATA_SUCCESS';
export const DASHBOARD_DATA_ERROR = 'DASHBOARD_DATA_ERROR';

export const FETCHING_SEARCH_DATA = 'FETCHING_SEARCH_DATA';
export const SEARCH_DATA_SUCCESS = 'SEARCH_DATA_SUCCESS';
export const SEARCH_DATA_ERROR = 'SEARCH_DATA_ERROR';

export const GENERIC_DATA_SUCCESS = 'GENERIC_DATA_SUCCESS';
export const GENERIC_DATA_ERROR = 'GENERIC_DATA_ERROR';
