export const strings = {
  filmKu: 'FilmKu',
  nowShowing: 'Now Showing',
  description: 'Description',
  cast: 'Cast',
  length: 'Length',
  Language: 'language',
  rating: 'Rating',
  seeMore: 'See More',
  popular: 'Popular',
  search: 'Search',
  ratings: 'Ratings',
  releaseDate: 'Release date',
  popularity: 'Popularity',
  noCastFound: 'No Cast found',
  noTitle: 'No Title',
  noDescription: 'No Description Available',
  requiredEmail: 'Email is Required',
  requiredPassword: 'Password is Required',
  invalidEmail: 'Invalid Email',
  invalidPassword: 'Invalid Password',
  userNotFound: 'User not found',
  accountCreated: 'Account created successfully',
  loginSuccess: 'Login SuccessFully',
  passwordValidation: 'Password should be at least 6 characters !',
  emailAlreadyUse: 'Email Already in use',
  registerToFilmKu: 'Register to Filmku',
  loginToFilmku: 'Login to Filmku',
  enterEmailId: 'Enter email Id',
  enterPassword: 'Enter Password',
  register: 'Register',
  dontHaveAnAccount: 'Dont have an account ? ',
  login: 'Login',
  haveAnAccount: 'Have an account ? ',
  blockedAccount:
    'Firebase has blocked your account Because of so many trial!!!',
};
